# Generated by Django 2.2.2 on 2019-07-31 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='user',
        ),
        migrations.AlterField(
            model_name='usertime',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 31, 10, 34, 28, 645699)),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 7, 31, 4, 49, 28, 645699, tzinfo=utc)),
        ),
    ]
