# Generated by Django 2.2.2 on 2019-07-31 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0002_auto_20190731_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 31, 10, 36, 38, 922615)),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 7, 31, 4, 51, 38, 922615, tzinfo=utc)),
        ),
    ]
