# Generated by Django 2.2.2 on 2019-07-31 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0004_auto_20190731_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
