# Generated by Django 2.2.2 on 2019-07-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0005_auto_20190731_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='user',
        ),
    ]
