# Generated by Django 2.2.2 on 2019-07-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0006_remove_usertime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertime',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='usertime',
            name='user',
            field=models.CharField(default='noone', max_length=300),
        ),
    ]
