# Generated by Django 2.2.2 on 2019-07-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0007_auto_20190731_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='usertime',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='user',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
