# Generated by Django 2.2.2 on 2019-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0008_auto_20190731_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='user',
        ),
        migrations.AddField(
            model_name='usertime',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
