# Generated by Django 2.2.2 on 2019-07-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userTime', '0009_auto_20190731_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertime',
            name='phone',
        ),
    ]
